language: python
python:
    - "3.6"

services:
    - docker

install:
    - pip install flake8
    - docker build . -t baselines_merl-test

script:
    - flake8 . --show-source --statistics
    - docker run -e RUNSLOW=1 baselines_merl-test pytest -v .
